export const AUTOMATION_TEMPLATES = [
  // ── E-COMMERCE ──────────────────────────────────────────────
  {
    name: "Nueva venta → WhatsApp",
    description: "Notifica por WhatsApp cuando Shopify registra una nueva venta con el detalle del pedido.",
    category: "ecommerce",
    trigger_type: "shopify.order",
    tags: ["shopify", "whatsapp", "ventas"],
    difficulty: "beginner",
    is_featured: true,
    config: { nombre: "Shopify → WhatsApp", trigger: { tipo: "shopify_order" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Nueva venta: {product} — ${total} · {customer}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Stock bajo → alerta equipo",
    description: "Detecta productos con stock crítico en Shopify y alerta al equipo por Slack o email.",
    category: "ecommerce",
    trigger_type: "schedule",
    tags: ["shopify", "slack", "inventario"],
    difficulty: "beginner",
    config: { nombre: "Stock bajo → Slack", trigger: { tipo: "schedule", frecuencia: "cada_hora" }, acciones: [{ tipo: "slack_send", canal: "#inventory", mensaje: "⚠️ Stock bajo: {product} - {quantity} unidades" }], frecuencia: "cada_hora" },
  },
  {
    name: "Venta Shopify → Google Sheets",
    description: "Registra cada venta automáticamente en una hoja de cálculo con cliente, producto y monto.",
    category: "ecommerce",
    trigger_type: "shopify.order",
    tags: ["shopify", "sheets", "reportes"],
    difficulty: "beginner",
    is_featured: true,
    config: { nombre: "Ventas → Sheets", trigger: { tipo: "shopify_order" }, acciones: [{ tipo: "sheets_append", hoja: "Ventas", fila: { fecha: "{date}", producto: "{product}", monto: "{total}", cliente: "{customer}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Post-venta: email de bienvenida",
    description: "Envía un email personalizado de agradecimiento después de cada compra.",
    category: "ecommerce",
    trigger_type: "shopify.order",
    tags: ["shopify", "email", "clientes"],
    difficulty: "beginner",
    config: { nombre: "Post-venta email", trigger: { tipo: "shopify_order" }, acciones: [{ tipo: "email_send", destinatario: "{customer_email}", asunto: "Gracias por tu compra", cuerpo: "Hola {customer}, tu pedido #{order_id} está en proceso." }], frecuencia: "tiempo_real" },
  },
  {
    name: "MercadoLibre: cambio de precio → alerta",
    description: "Monitorea precios de competidores en MercadoLibre y avisa si hay cambios significativos.",
    category: "ecommerce",
    trigger_type: "schedule",
    tags: ["mercadolibre", "precio", "monitoreo"],
    difficulty: "intermediate",
    config: { nombre: "Precio ML → alerta", trigger: { tipo: "schedule", frecuencia: "cada_hora" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Cambio de precio detectado en ML: {product} {change}%" }], frecuencia: "cada_hora" },
  },
  {
    name: "Reseña negativa → ticket soporte",
    description: "Crea automáticamente un ticket de soporte cuando se detecta una reseña de 1-2 estrellas.",
    category: "ecommerce",
    trigger_type: "webhook",
    tags: ["soporte", "reseñas", "clientes"],
    difficulty: "intermediate",
    config: { nombre: "Reseña negativa → ticket", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", destinatario: "soporte@empresa.com", asunto: "Reseña negativa: {product}", cuerpo: "Cliente: {customer}\nRating: {rating}\nComentario: {review}" }], frecuencia: "tiempo_real" },
  },

  // ── COMUNICACIÓN ─────────────────────────────────────────────
  {
    name: "Email con factura → Drive + Sheets",
    description: "Extrae datos de facturas recibidas por email y las guarda en Drive y registra en Sheets.",
    category: "finance",
    trigger_type: "gmail.trigger",
    tags: ["gmail", "drive", "sheets", "facturas"],
    difficulty: "intermediate",
    is_featured: true,
    config: { nombre: "Factura email → Drive", trigger: { tipo: "gmail_trigger", filtro: "factura OR invoice" }, acciones: [{ tipo: "drive_upload", url: "/facturas/{year}/{month}/" }, { tipo: "sheets_append", hoja: "Facturas", fila: { fecha: "{date}", proveedor: "{from}", monto: "{amount}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Email de soporte → Notion + WhatsApp",
    description: "Registra tickets de soporte en Notion y notifica al equipo de soporte por WhatsApp.",
    category: "communication",
    trigger_type: "gmail.trigger",
    tags: ["gmail", "notion", "whatsapp", "soporte"],
    difficulty: "beginner",
    config: { nombre: "Soporte email → Notion", trigger: { tipo: "gmail_trigger", filtro: "soporte OR ayuda OR problema" }, acciones: [{ tipo: "notion_create", base: "Tickets" }, { tipo: "whatsapp_send", mensaje: "Nuevo ticket: {subject} de {from}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Newsletter semanal automático",
    description: "Recopila noticias del sector, las resume con IA y envía el newsletter cada lunes.",
    category: "communication",
    trigger_type: "schedule",
    tags: ["email", "newsletter", "IA", "scraping"],
    difficulty: "advanced",
    is_featured: true,
    config: { nombre: "Newsletter semanal", trigger: { tipo: "schedule", frecuencia: "semanal" }, acciones: [{ tipo: "web_scrape", url: "https://news.ycombinator.com" }, { tipo: "email_send", asunto: "Newsletter semanal — {date}" }], frecuencia: "semanal" },
  },
  {
    name: "WhatsApp → crear tarea en Notion",
    description: "Convierte mensajes de WhatsApp en tareas en Notion automáticamente.",
    category: "communication",
    trigger_type: "whatsapp.message",
    tags: ["whatsapp", "notion", "tareas"],
    difficulty: "beginner",
    config: { nombre: "WhatsApp → Notion tarea", trigger: { tipo: "whatsapp_message" }, acciones: [{ tipo: "notion_create", base: "Tareas", campos: { tarea: "{message}", origen: "WhatsApp", fecha: "{date}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Slack mensaje → ticket Jira/Airtable",
    description: "Convierte mensajes en Slack que comienzan con '!ticket' en tickets de soporte.",
    category: "communication",
    trigger_type: "slack.message",
    tags: ["slack", "airtable", "tickets"],
    difficulty: "beginner",
    config: { nombre: "Slack → ticket", trigger: { tipo: "slack_message", filtro: "!ticket" }, acciones: [{ tipo: "airtable_create", base: "Tickets", campos: { titulo: "{message}", creado_por: "{user}", canal: "{channel}" } }], frecuencia: "tiempo_real" },
  },

  // ── FINANZAS ─────────────────────────────────────────────────
  {
    name: "Reporte financiero semanal",
    description: "Consolida datos de ventas y gastos del período y envía un reporte PDF a gerencia.",
    category: "finance",
    trigger_type: "schedule",
    tags: ["sheets", "email", "reportes", "finanzas"],
    difficulty: "intermediate",
    is_featured: true,
    config: { nombre: "Reporte semanal finanzas", trigger: { tipo: "schedule", frecuencia: "semanal" }, acciones: [{ tipo: "sheets_read", hoja: "Ventas" }, { tipo: "email_send", asunto: "Reporte semanal {date}", cuerpo: "Adjunto el reporte financiero de la semana." }], frecuencia: "semanal" },
  },
  {
    name: "Gasto supera presupuesto → alerta",
    description: "Detecta cuando un gasto supera el presupuesto mensual definido y alerta al responsable.",
    category: "finance",
    trigger_type: "schedule",
    tags: ["sheets", "email", "presupuesto"],
    difficulty: "beginner",
    config: { nombre: "Alerta presupuesto", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "email_send", destinatario: "finanzas@empresa.com", asunto: "⚠️ Presupuesto superado: {categoria}", cuerpo: "El gasto en {categoria} superó el presupuesto mensual." }], frecuencia: "diaria" },
  },
  {
    name: "Pago recibido Stripe → Notion CRM",
    description: "Registra cada pago recibido en Stripe en la base de datos de clientes de Notion.",
    category: "finance",
    trigger_type: "webhook",
    tags: ["stripe", "notion", "pagos"],
    difficulty: "beginner",
    config: { nombre: "Stripe → Notion", trigger: { tipo: "webhook" }, acciones: [{ tipo: "notion_create", base: "Clientes", campos: { nombre: "{customer}", monto: "{amount}", fecha: "{date}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Conciliación bancaria automática",
    description: "Compara movimientos bancarios con registros en Sheets y marca las diferencias.",
    category: "finance",
    trigger_type: "schedule",
    tags: ["sheets", "finanzas", "conciliación"],
    difficulty: "advanced",
    config: { nombre: "Conciliación bancaria", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "sheets_read", hoja: "Movimientos" }, { tipo: "sheets_write", hoja: "Conciliación" }], frecuencia: "diaria" },
  },

  // ── VENTAS / CRM ─────────────────────────────────────────────
  {
    name: "Lead nuevo → HubSpot + WhatsApp",
    description: "Cuando llega un lead desde formulario, lo crea en HubSpot y notifica al vendedor por WhatsApp.",
    category: "sales",
    trigger_type: "webhook",
    tags: ["hubspot", "whatsapp", "leads"],
    difficulty: "beginner",
    is_featured: true,
    config: { nombre: "Lead → HubSpot", trigger: { tipo: "webhook" }, acciones: [{ tipo: "hubspot_create", campos: { nombre: "{name}", email: "{email}", origen: "{source}" } }, { tipo: "whatsapp_send", mensaje: "Nuevo lead: {name} ({email}) — {source}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Follow-up automático 24hs",
    description: "Envía un email de seguimiento 24 horas después del primer contacto con un prospecto.",
    category: "sales",
    trigger_type: "schedule",
    tags: ["email", "crm", "follow-up"],
    difficulty: "intermediate",
    config: { nombre: "Follow-up 24hs", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "email_send", asunto: "¿Pudiste revisar nuestra propuesta?", cuerpo: "Hola {name}, quería hacer un seguimiento..." }], frecuencia: "diaria" },
  },
  {
    name: "Deal cerrado → onboarding cliente",
    description: "Al cerrar un deal en HubSpot, inicia el proceso de onboarding del cliente automáticamente.",
    category: "sales",
    trigger_type: "hubspot.deal",
    tags: ["hubspot", "email", "onboarding"],
    difficulty: "intermediate",
    config: { nombre: "Deal cerrado → onboarding", trigger: { tipo: "hubspot_deal", filtro: "stage:closed_won" }, acciones: [{ tipo: "email_send", asunto: "¡Bienvenido a bordo, {name}!", cuerpo: "Estamos listos para empezar. Tu acceso está disponible en:" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Propuesta sin respuesta → recordatorio",
    description: "Si una propuesta enviada no tiene respuesta en 3 días, envía un recordatorio automático.",
    category: "sales",
    trigger_type: "schedule",
    tags: ["email", "ventas", "recordatorio"],
    difficulty: "beginner",
    config: { nombre: "Recordatorio propuesta", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "email_send", asunto: "Recordatorio: propuesta #{id}", cuerpo: "Hola {name}, ¿tuviste oportunidad de revisar nuestra propuesta?" }], frecuencia: "diaria" },
  },

  // ── RRHH ─────────────────────────────────────────────────────
  {
    name: "CV recibido → clasificar + notificar",
    description: "Procesa CVs recibidos por email con IA, los clasifica y notifica al área de RRHH.",
    category: "hr",
    trigger_type: "gmail.trigger",
    tags: ["gmail", "rrhh", "IA", "reclutamiento"],
    difficulty: "intermediate",
    is_featured: true,
    config: { nombre: "CV → clasificar", trigger: { tipo: "gmail_trigger", filtro: "CV OR curriculum OR postulación" }, acciones: [{ tipo: "drive_upload", url: "/rrhh/cvs/{year}/" }, { tipo: "slack_send", canal: "#rrhh", mensaje: "Nuevo CV recibido: {from} — {subject}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Onboarding nuevo empleado",
    description: "Al ingresar un empleado, crea accesos, envía bienvenida y crea checklist de tareas.",
    category: "hr",
    trigger_type: "webhook",
    tags: ["onboarding", "email", "notion", "rrhh"],
    difficulty: "intermediate",
    config: { nombre: "Onboarding empleado", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", asunto: "Bienvenido/a al equipo, {name}!", cuerpo: "Tu primer día es el {start_date}. Aquí está toda la información:" }, { tipo: "notion_create", base: "Onboarding", campos: { empleado: "{name}", inicio: "{start_date}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Solicitud de vacaciones → aprobación",
    description: "Gestiona solicitudes de vacaciones: notifica al manager y actualiza el calendario.",
    category: "hr",
    trigger_type: "webhook",
    tags: ["rrhh", "vacaciones", "calendar", "email"],
    difficulty: "beginner",
    config: { nombre: "Solicitud vacaciones", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", destinatario: "manager@empresa.com", asunto: "Solicitud de vacaciones: {employee}", cuerpo: "{employee} solicita vacaciones del {from} al {to}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Cumpleaños empleados → Slack",
    description: "Cada mañana revisa si hay cumpleaños en el equipo y envía felicitaciones a Slack.",
    category: "hr",
    trigger_type: "schedule",
    tags: ["rrhh", "slack", "team"],
    difficulty: "beginner",
    config: { nombre: "Cumpleaños → Slack", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "slack_send", canal: "#general", mensaje: "🎉 ¡Hoy es el cumpleaños de {name}! Felicitaciones!" }], frecuencia: "diaria" },
  },

  // ── INTELIGENCIA / SCRAPING ──────────────────────────────────
  {
    name: "Monitor noticias del sector",
    description: "Scrapea noticias relevantes del sector cada mañana y envía un resumen por email.",
    category: "intelligence",
    trigger_type: "schedule",
    tags: ["scraping", "email", "IA", "noticias"],
    difficulty: "intermediate",
    is_featured: true,
    config: { nombre: "Monitor noticias", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "web_scrape", url: "https://news.ycombinator.com" }, { tipo: "email_send", asunto: "Noticias del sector — {date}" }], frecuencia: "diaria" },
  },
  {
    name: "Monitoreo de competidores",
    description: "Rastrea cambios en sitios de competidores (precios, productos, ofertas) y alerta.",
    category: "intelligence",
    trigger_type: "schedule",
    tags: ["scraping", "competidores", "monitoreo"],
    difficulty: "intermediate",
    config: { nombre: "Monitor competidores", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "web_scrape", url: "{competitor_url}" }, { tipo: "slack_send", canal: "#competencia", mensaje: "Cambio detectado en {competitor}: {change}" }], frecuencia: "diaria" },
  },
  {
    name: "Reporte de tendencias semanales",
    description: "Analiza Google Trends y redes sociales para identificar tendencias del nicho.",
    category: "intelligence",
    trigger_type: "schedule",
    tags: ["tendencias", "IA", "reportes", "semanal"],
    difficulty: "advanced",
    config: { nombre: "Tendencias semanales", trigger: { tipo: "schedule", frecuencia: "semanal" }, acciones: [{ tipo: "email_send", asunto: "Tendencias de la semana — {date}" }], frecuencia: "semanal" },
  },
  {
    name: "Análisis de reviews de producto",
    description: "Analiza con IA las reseñas de tu producto en internet y genera un reporte de sentimiento.",
    category: "intelligence",
    trigger_type: "schedule",
    tags: ["IA", "reviews", "sentimiento", "scraping"],
    difficulty: "advanced",
    config: { nombre: "Análisis reviews", trigger: { tipo: "schedule", frecuencia: "semanal" }, acciones: [{ tipo: "web_scrape", url: "{product_url}" }, { tipo: "email_send", asunto: "Análisis reviews — {product}" }], frecuencia: "semanal" },
  },

  // ── SALUD ────────────────────────────────────────────────────
  {
    name: "Recordatorio de turno 48hs antes",
    description: "Envía recordatorios automáticos a pacientes 48 horas antes de su turno médico.",
    category: "healthcare",
    trigger_type: "schedule",
    tags: ["salud", "whatsapp", "turnos", "recordatorio"],
    difficulty: "beginner",
    is_featured: true,
    config: { nombre: "Recordatorio turno", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Recordatorio: su turno con el Dr. {doctor} es mañana a las {time}." }], frecuencia: "diaria" },
  },
  {
    name: "Confirmación de turno → Google Calendar",
    description: "Crea eventos en Google Calendar automáticamente cuando se confirma un turno.",
    category: "healthcare",
    trigger_type: "webhook",
    tags: ["salud", "calendar", "turnos"],
    difficulty: "beginner",
    config: { nombre: "Turno → Calendar", trigger: { tipo: "webhook" }, acciones: [{ tipo: "calendar_create", titulo: "Turno: {patient} — Dr. {doctor}", inicio: "{datetime}", duracion: 30 }], frecuencia: "tiempo_real" },
  },
  {
    name: "Alta médica → ficha digital",
    description: "Procesa el formulario de alta del paciente y actualiza la ficha digital automáticamente.",
    category: "healthcare",
    trigger_type: "webhook",
    tags: ["salud", "sheets", "pacientes"],
    difficulty: "intermediate",
    config: { nombre: "Alta → ficha digital", trigger: { tipo: "webhook" }, acciones: [{ tipo: "sheets_append", hoja: "Pacientes", fila: { nombre: "{patient}", fecha_alta: "{date}", diagnostico: "{diagnosis}" } }], frecuencia: "tiempo_real" },
  },

  // ── MARKETING ────────────────────────────────────────────────
  {
    name: "Publicar en redes al publicar blog",
    description: "Cuando publicas un artículo en el blog, comparte automáticamente en Instagram, Twitter y LinkedIn.",
    category: "marketing",
    trigger_type: "webhook",
    tags: ["redes sociales", "blog", "marketing"],
    difficulty: "intermediate",
    config: { nombre: "Blog → redes sociales", trigger: { tipo: "webhook" }, acciones: [{ tipo: "instagram_post", mensaje: "Nuevo artículo: {title} - {url}" }, { tipo: "slack_send", canal: "#marketing", mensaje: "✅ Publicado en redes: {title}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Lead magnet descargado → nurturing",
    description: "Cuando alguien descarga un lead magnet, inicia automáticamente una secuencia de nurturing.",
    category: "marketing",
    trigger_type: "webhook",
    tags: ["email", "leads", "nurturing", "marketing"],
    difficulty: "intermediate",
    is_featured: true,
    config: { nombre: "Lead magnet → nurturing", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", asunto: "Aquí está tu {resource_name}", cuerpo: "Hola {name}, gracias por descargar {resource_name}. Aquí está el link:" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Reporte mensual de redes sociales",
    description: "Genera un reporte mensual con métricas de redes sociales y lo envía a marketing.",
    category: "marketing",
    trigger_type: "schedule",
    tags: ["redes", "reportes", "mensual"],
    difficulty: "intermediate",
    config: { nombre: "Reporte redes mensual", trigger: { tipo: "schedule", frecuencia: "mensual" }, acciones: [{ tipo: "email_send", asunto: "Reporte redes sociales — {month}", cuerpo: "Adjunto el reporte del mes." }], frecuencia: "mensual" },
  },
  {
    name: "Mención en redes → alerta marketing",
    description: "Detecta menciones de la marca en redes sociales y alerta al equipo de marketing.",
    category: "marketing",
    trigger_type: "webhook",
    tags: ["redes", "marca", "alertas", "marketing"],
    difficulty: "intermediate",
    config: { nombre: "Mención marca → alerta", trigger: { tipo: "webhook" }, acciones: [{ tipo: "slack_send", canal: "#marketing", mensaje: "📢 Mención de la marca en {platform}: {text} — {url}" }], frecuencia: "tiempo_real" },
  },

  // ── OPERACIONES ───────────────────────────────────────────────
  {
    name: "Backup diario de Sheets a Drive",
    description: "Crea un backup automático de todas las hojas de cálculo importantes cada noche.",
    category: "operations",
    trigger_type: "schedule",
    tags: ["backup", "drive", "sheets"],
    difficulty: "beginner",
    config: { nombre: "Backup diario", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "drive_upload", url: "/backups/{date}/" }], frecuencia: "diaria" },
  },
  {
    name: "Formulario → registrar en Airtable",
    description: "Captura respuestas de cualquier formulario y las registra en Airtable automáticamente.",
    category: "operations",
    trigger_type: "webhook",
    tags: ["formulario", "airtable", "datos"],
    difficulty: "beginner",
    config: { nombre: "Formulario → Airtable", trigger: { tipo: "webhook" }, acciones: [{ tipo: "airtable_create", base: "Respuestas", campos: { nombre: "{name}", email: "{email}", respuesta: "{answer}" } }], frecuencia: "tiempo_real" },
  },
  {
    name: "Sincronización Sheets ↔ Airtable",
    description: "Sincroniza datos entre Google Sheets y Airtable de forma bidireccional cada hora.",
    category: "operations",
    trigger_type: "schedule",
    tags: ["sheets", "airtable", "sync"],
    difficulty: "intermediate",
    config: { nombre: "Sheets ↔ Airtable sync", trigger: { tipo: "schedule", frecuencia: "cada_hora" }, acciones: [{ tipo: "sheets_read", hoja: "Datos" }, { tipo: "airtable_update", base: "Datos" }], frecuencia: "cada_hora" },
  },
  {
    name: "Monitor de uptime → alerta Slack",
    description: "Comprueba cada 5 minutos si tu sitio web está activo y alerta si hay caída.",
    category: "operations",
    trigger_type: "schedule",
    tags: ["uptime", "slack", "monitoreo"],
    difficulty: "beginner",
    config: { nombre: "Monitor uptime", trigger: { tipo: "schedule", frecuencia: "cada_hora" }, acciones: [{ tipo: "slack_send", canal: "#alertas", mensaje: "⚠️ Caída detectada en {url} — {time}" }], frecuencia: "cada_hora" },
  },
  {
    name: "Informe diario de operaciones",
    description: "Consolida el resumen del día de todos los sistemas y lo envía a gerencia cada tarde.",
    category: "operations",
    trigger_type: "schedule",
    tags: ["reportes", "email", "operaciones", "diario"],
    difficulty: "intermediate",
    config: { nombre: "Informe diario ops", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "email_send", asunto: "Informe diario de operaciones — {date}" }], frecuencia: "diaria" },
  },

  // ── AGENCIAS / CREATIVOS ─────────────────────────────────────
  {
    name: "Brief de cliente → propuesta automática",
    description: "Cuando llega un brief por email, genera una propuesta inicial con IA y la notifica al equipo.",
    category: "agencies",
    trigger_type: "gmail.trigger",
    tags: ["agencia", "email", "IA", "propuesta"],
    difficulty: "advanced",
    config: { nombre: "Brief → propuesta", trigger: { tipo: "gmail_trigger", filtro: "brief OR proyecto OR propuesta" }, acciones: [{ tipo: "slack_send", canal: "#nuevos-proyectos", mensaje: "Nuevo brief de {from}: {subject}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Aprobación de contenido → publicar",
    description: "Cuando el cliente aprueba contenido en un formulario, lo publica automáticamente en redes.",
    category: "agencies",
    trigger_type: "webhook",
    tags: ["agencia", "redes", "aprobación", "contenido"],
    difficulty: "intermediate",
    config: { nombre: "Aprobación → publicar", trigger: { tipo: "webhook" }, acciones: [{ tipo: "instagram_post", mensaje: "{caption}" }, { tipo: "slack_send", canal: "#publicaciones", mensaje: "✅ Contenido publicado para {client}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Reporte mensual a cliente",
    description: "Genera y envía un reporte mensual de resultados al cliente automáticamente.",
    category: "agencies",
    trigger_type: "schedule",
    tags: ["agencia", "reportes", "cliente", "mensual"],
    difficulty: "intermediate",
    config: { nombre: "Reporte mensual cliente", trigger: { tipo: "schedule", frecuencia: "mensual" }, acciones: [{ tipo: "email_send", asunto: "Reporte mensual de resultados — {client} — {month}", cuerpo: "Estimado/a {client}, adjuntamos el reporte del mes:" }], frecuencia: "mensual" },
  },

  // ── LEGAL / CONTRATOS ────────────────────────────────────────
  {
    name: "Contrato firmado → onboarding",
    description: "Al recibir un contrato firmado por email, inicia el proceso de onboarding del cliente.",
    category: "operations",
    trigger_type: "gmail.trigger",
    tags: ["contratos", "onboarding", "email"],
    difficulty: "beginner",
    config: { nombre: "Contrato firmado → onboarding", trigger: { tipo: "gmail_trigger", filtro: "contrato firmado OR signed contract" }, acciones: [{ tipo: "drive_upload", url: "/contratos/{year}/" }, { tipo: "email_send", asunto: "¡Bienvenido! Próximos pasos", cuerpo: "Recibimos tu contrato firmado. Aquí están los próximos pasos:" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Vencimiento de contrato → renovación",
    description: "30 días antes del vencimiento de un contrato, notifica al equipo de ventas para iniciar renovación.",
    category: "operations",
    trigger_type: "schedule",
    tags: ["contratos", "renovación", "email"],
    difficulty: "intermediate",
    config: { nombre: "Vencimiento contrato → alerta", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "slack_send", canal: "#ventas", mensaje: "⚠️ Contrato de {client} vence en 30 días" }, { tipo: "email_send", destinatario: "ventas@empresa.com", asunto: "Renovación pendiente: {client}" }], frecuencia: "diaria" },
  },

  // ── EDUCACIÓN ────────────────────────────────────────────────
  {
    name: "Inscripción a curso → bienvenida",
    description: "Cuando alguien se inscribe a un curso, envía emails de bienvenida y acceso a la plataforma.",
    category: "education",
    trigger_type: "webhook",
    tags: ["educación", "email", "inscripción"],
    difficulty: "beginner",
    config: { nombre: "Inscripción → bienvenida", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", asunto: "¡Bienvenido/a al curso {course}!", cuerpo: "Hola {name}, tu acceso al curso {course} ya está listo." }], frecuencia: "tiempo_real" },
  },
  {
    name: "Recordatorio de tarea pendiente",
    description: "Envía recordatorios a estudiantes con tareas pendientes 24 horas antes del vencimiento.",
    category: "education",
    trigger_type: "schedule",
    tags: ["educación", "whatsapp", "recordatorio"],
    difficulty: "beginner",
    config: { nombre: "Recordatorio tarea", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Recordatorio: Tienes la tarea '{task}' pendiente para mañana." }], frecuencia: "diaria" },
  },
  {
    name: "Certificado de finalización automático",
    description: "Genera y envía el certificado de finalización cuando un alumno completa el 100% del curso.",
    category: "education",
    trigger_type: "webhook",
    tags: ["educación", "certificado", "email"],
    difficulty: "intermediate",
    config: { nombre: "Certificado automático", trigger: { tipo: "webhook" }, acciones: [{ tipo: "email_send", asunto: "🎓 Tu certificado de {course}", cuerpo: "Felicitaciones {name}! Completaste {course}. Tu certificado está adjunto." }], frecuencia: "tiempo_real" },
  },

  // ── INMOBILIARIO ─────────────────────────────────────────────
  {
    name: "Lead inmobiliario → CRM + WhatsApp",
    description: "Captura leads de portales inmobiliarios y los registra en el CRM con alerta al asesor.",
    category: "realestate",
    trigger_type: "webhook",
    tags: ["inmobiliaria", "leads", "whatsapp", "crm"],
    difficulty: "beginner",
    config: { nombre: "Lead inmobiliario", trigger: { tipo: "webhook" }, acciones: [{ tipo: "sheets_append", hoja: "Leads", fila: { nombre: "{name}", propiedad: "{property}", contacto: "{phone}" } }, { tipo: "whatsapp_send", mensaje: "Nuevo lead: {name} interesado en {property}" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Visita agendada → recordatorio 24hs",
    description: "Envía recordatorios automáticos de visitas a propiedades 24 horas antes.",
    category: "realestate",
    trigger_type: "schedule",
    tags: ["inmobiliaria", "whatsapp", "turnos"],
    difficulty: "beginner",
    config: { nombre: "Visita → recordatorio", trigger: { tipo: "schedule", frecuencia: "diaria" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Recordatorio: mañana a las {time} tienes una visita en {property}. ¿Confirmás?" }], frecuencia: "diaria" },
  },

  // ── RESTAURANT / GASTRONOMÍA ────────────────────────────────
  {
    name: "Reserva confirmada → WhatsApp",
    description: "Envía confirmación por WhatsApp cuando se realiza una reserva en el restaurante.",
    category: "hospitality",
    trigger_type: "webhook",
    tags: ["restaurante", "whatsapp", "reservas"],
    difficulty: "beginner",
    config: { nombre: "Reserva → WhatsApp", trigger: { tipo: "webhook" }, acciones: [{ tipo: "whatsapp_send", mensaje: "Reserva confirmada para {guests} personas el {date} a las {time}. ¡Los esperamos!" }], frecuencia: "tiempo_real" },
  },
  {
    name: "Review en Google → respuesta automática",
    description: "Detecta nuevas reseñas en Google My Business y prepara una respuesta personalizada con IA.",
    category: "hospitality",
    trigger_type: "webhook",
    tags: ["restaurante", "reviews", "google", "IA"],
    difficulty: "intermediate",
    config: { nombre: "Review Google → respuesta", trigger: { tipo: "webhook" }, acciones: [{ tipo: "slack_send", canal: "#reviews", mensaje: "Nueva reseña ({rating}⭐): {review}" }], frecuencia: "tiempo_real" },
  },
] as const;

export type TemplateCategory =
  | "ecommerce" | "finance" | "communication" | "sales"
  | "hr" | "intelligence" | "healthcare" | "marketing"
  | "operations" | "agencies" | "education" | "realestate" | "hospitality";

export const CATEGORY_LABELS: Record<string, string> = {
  ecommerce: "E-commerce",
  finance: "Finanzas",
  communication: "Comunicación",
  sales: "Ventas",
  hr: "RRHH",
  intelligence: "Inteligencia",
  healthcare: "Salud",
  marketing: "Marketing",
  operations: "Operaciones",
  agencies: "Agencias",
  education: "Educación",
  realestate: "Inmobiliario",
  hospitality: "Gastronomía",
};
